version: "3.7"

services:
  gateway:
    # Gives container a friendly name
    container_name: gateway
    # Directory where Dockerfile is located
    build:
      context: ./gateway
    # Map port 5000 on local machine to port 80 in container
    ports:
      - "5000:80"
    # Set environment to Preproduction for now
    environment:
      - ASPNETCORE_ENVIRONMENT=Preproduction

  service1:
    # Gives container a friendly name
    container_name: service1
    # Directory where Dockerfile is located
    build:
      context: ./service1
  service2:
    # Gives container a friendly name. Especially important for .Net debugging
    container_name: service2
    # .Net is one directory further in due to build artifact mapping in Directory.Build.props
    build:
      context: ./service2/src
