{{- $mount := dict "val" .Values.handoverOptions "basePath" .Values.mountBasePath -}}
{{- with .Values.handoverOptions }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: handover-options
  labels:
    version: {{ .version | quote}}
spec:
  replicas: {{ .replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: {{ $.Release.Namespace }}
      labels:
        app: handover-options
    spec:
      hostname: handover-options
      containers:
        - name: handover-options
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          image: {{ .image }}
          ports:
            - containerPort: 8001
            - containerPort: 9229 # TODO Move this to values-file
          {{- include "default.volumeMounts" $mount | nindent 10 -}}
      {{- include "default.volumes" $mount | nindent 6 -}}
      {{- if $.Values.inAzure }}
      imagePullSecrets:
        - name: {{ $.Values.registry.secretName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: handover-options
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .type }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: handover-options
{{- end }}