apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-config
  namespace: {{.Release.Namespace}}
data:
  ssl-redirect: "false"
  hsts: "false"
  disable-ipv6: "true"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{.Release.Namespace}}
  name: default-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.inAzure}}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end}}
spec:
  rules: 
    - http:
        paths:
          {{- include "default.ingress.paths" . | nindent 10 }}
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{.Release.Namespace}}
  name: ingress-nginx
spec:
  type: NodePort
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      nodePort: {{.Values.ingress.nodePort}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: {{.Release.Namespace}}
  name: ingress-nginx
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{.Release.Namespace}}
      labels:
        app: ingress-nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0
          name: ingress-nginx
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - /nginx-ingress-controller
            - --default-backend-service={{.Release.Namespace}}/nginx-default-backend
            - --configmap={{.Release.Namespace}}/nginx-ingress-config
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{.Release.Namespace}}
  name: nginx-default-backend
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: nginx-default-backend
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: {{.Release.Namespace}}
  name: nginx-default-backend
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{.Release.Namespace}}
      labels:
        app: nginx-default-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: default-http-backend
          image: gcr.io/google_containers/defaultbackend:1.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
