{{- $mount := dict "val" .Values.stores "basePath" .Values.mountBasePath -}}
{{- with .Values.stores }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stores
  labels:
    version: {{ .version | quote}}
spec:
  replicas: {{ .replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: {{ $.Release.Namespace }}
      labels:
        app: stores
    spec:
      hostname: stores
      containers:
        - name: stores
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          image: {{ .image }}
          ports:
            - containerPort: 8002
            - containerPort: 9229 # TODO Move this to values-file
          {{- include "default.volumeMounts" $mount | nindent 10 -}}
      {{- include "default.volumes" $mount | nindent 6 -}}
      {{- if $.Values.inAzure }}
      imagePullSecrets:
        - name: {{ $.Values.registry.secretName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: stores
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ .type }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: stores
{{- end }}