pool:
  vmImage: "Ubuntu 16.04"

variables:
  imageName: "$(serviceName):$(build.buildId)"

steps:
  - script: docker build -t $(imageName) ./$(serviceName)
    displayName: "Build service image: $(serviceName)"
  - displayName: "Push image"
    script: |
      docker login -u $(dockerId) -p $(pswd)
      docker push $(dockerId)/$(imageName)
