pool:
  vmImage: "Ubuntu 16.04"

variables:
  registryName: "$(dockerId).azurecr.io"
  imageName: "$(registryName)/$(serviceName):$(build.buildId)"

steps:
  - script: docker build -t $(imageName) ./$(serviceName)
    displayName: "Build service image: $(serviceName)"
  - script: |
      docker login -u $(dockerId) -p $(pswd) $(registryName)
      docker push $(imageName)
    displayName: "Push image"
