apiVersion: v1
kind: Namespace
metadata:
  name: #{Release.EnvironmentName}#
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: #{dockerId}.azurecr.io/service1:#{Release.Artifacts.Service1.BuildId}"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: #{dockerId}.azurecr.io/service2:#{Release.Artifacts.Service2.BuildId}"
