# This is run by our CI system for deployment to Azure
inAzure: true
# Information about Azure Container Registry Secrets
# Used to authenticate when pulling images
registry:
  secretName: #{secretName}

# Pull new images if not present
imagePullPolicy: IfNotPresent

ingress:
  # Combined with inAzure-flag, this creates an internal loadbalancer in AKS
  type: LoadBalancer
  # Setting a static external IP to the Ingress Loadbalancer
  externalIp: #{externalIp}
  # Whitelisting the ip of application management gateway
  whitelist: "#{apimIp}/32"

# Service 1 Prod specific settings
service1:
  # Run multiple replicas in prod
  replicas: 2
  # Which version of the service. Used as a label
  version: "#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}"
  # Which image to use. Must exist in Azure Container Registry
  image: #{registryName}/service1:#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}
  # Since we needed to override ports in dev, we must specify in cloud config
  ports:
    - protocol: TCP
      port: 8001

handover-options:
  # Run multiple replicas in prod
  replicas: 2
  # Which version of the service. Used as a label
  version: "#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}"
  # Which image to use. Must exist in Azure Container Registry
  image: #{registryName}/service1:#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}
  # Since we needed to override ports in dev, we must specify in cloud config
  ports:
    - protocol: TCP
      port: 8001

stores:
  # Run multiple replicas in prod
  replicas: 2
  # Which version of the service. Used as a label
  version: "#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}"
  # Which image to use. Must exist in Azure Container Registry
  image: #{registryName}/service1:#{RELEASE_ARTIFACTS__SERVICE1_BUILDNUMBER}
  # Since we needed to override ports in dev, we must specify in cloud config
  ports:
    - protocol: TCP
      port: 8001

service2:
  replicas: 2
  version: "#{RELEASE_ARTIFACTS__SERVICE2_BUILDNUMBER}"
  image: #{registryName}/service2:#{RELEASE_ARTIFACTS__SERVICE2_BUILDNUMBER}
