pool:
  vmImage: "Ubuntu 16.04"

# This is actually the build number format specifier
name: $(Date:yyyyMMdd)$(Rev:.r)

steps:
  # Task to copy kubernetes configuration to artifact directory
  - task: CopyFiles@2
    inputs:
      contents: Infrastructure/kubernetes.yml
      targetFolder: $(Build.ArtifactStagingDirectory)
  # Task to publish artifact directory (making them available in deploy)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: provisioning

 - powershell: |
      Write-Host "git tag $env:tag"
      git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" tag $env:tag
      git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin $env:tag
    displayName: Tag provision build in git
    workingDirectory: $(Build.SourcesDirectory)
    env:
      tag: "Provisioning-$(build.buildNumber)"
      SYSTEM_ACCESSTOKEN: $(system.accesstoken)
    ignoreLASTEXITCODE: false
    errorActionPreference: Stop
    failOnStderr: false
